CREATE TABLE `ods_emp_roster` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键ID',
  `emp_code` VARCHAR(32) NOT NULL COMMENT '人员编码（员工工号，唯一）',
  `emp_name` VARCHAR(50) NOT NULL COMMENT '员工姓名',
  `dept_name` VARCHAR(100) DEFAULT NULL COMMENT '所属部门',
  `sub_dept_name` VARCHAR(100) DEFAULT NULL COMMENT '下设部门/二级部门',
  `emp_category` VARCHAR(50) DEFAULT NULL COMMENT '人员类别（合同制员工（在岗））',
  `post_name` VARCHAR(100) DEFAULT NULL COMMENT '岗位名称',
  `post_grade` VARCHAR(50) DEFAULT NULL COMMENT '岗位等级（P）',
  `five_series` VARCHAR(50) DEFAULT NULL COMMENT '五大序列（管理/技术/员工等）',
  `gender` CHAR(2) DEFAULT NULL COMMENT '性别（男/女）',
  `birth_date` DATE DEFAULT NULL COMMENT '出生日期',
  `political_status` VARCHAR(30) DEFAULT NULL COMMENT '政治面貌',
  `nation` VARCHAR(30) DEFAULT NULL COMMENT '民族',
  `highest_edu` VARCHAR(50) DEFAULT NULL COMMENT '最高学历',
  `highest_edu_school` VARCHAR(200) DEFAULT NULL COMMENT '最高学历毕业院校',
  `highest_edu_major` VARCHAR(100) DEFAULT NULL COMMENT '最高学历所学专业',
  `contract_term_type` VARCHAR(50) DEFAULT NULL COMMENT '合同期限类型（固定期限/无固定期限等）',
  `contract_end_date` DATE DEFAULT NULL COMMENT '合同终止日期',
  `dept_category` VARCHAR(50) DEFAULT NULL COMMENT '部门类别（研发/销售/行政等）',
  `labor_relation_company` VARCHAR(200) DEFAULT NULL COMMENT '劳动关系所属公司名称',
  `work_location` VARCHAR(200) DEFAULT NULL COMMENT '工作地点',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '数据录入时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_emp_code` (`emp_code`) USING BTREE COMMENT '员工编码唯一索引'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='员工花名册表' ROW_FORMAT=DYNAMIC;
